# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0002_auto_20160812_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswers',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
