# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqs', '0003_studentanswers_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswers',
            name='quiz_title',
            field=models.CharField(default=b'title', max_length=100),
        ),
    ]
